version: '3.4'
services:
  worker:
    image: localhost:5000/worker
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
    deploy:
      mode: replicated
      replicas: 1

  walkoff_app_sdk:
    build:
      context: ../app_sdk
      dockerfile: ./Dockerfile
    image: localhost:5000/walkoff_app_sdk

